# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
#image: gradle:alpine
default:
  image: azul/zulu-openjdk:21-latest
  tags: [$RUNNER_TAGS]

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - test-libs

unitTests:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  stage: test-libs
  script:
    - ./gradlew test --stacktrace
    - ./gradlew publishMavenJavaPublicationToGitLabRepository --stacktrace
  artifacts:
    when: on_failure
    reports:
      junit: "**/build/test-results/test/TEST-*.xml"