name: test_and_publish

on:
  push:
  workflow_dispatch:  # Allows manual execution

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04-arm, windows-2019, macos-13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Testing
        run: ./gradlew test --stacktrace

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

    publish:
      needs: test  # Only runs if 'test' succeeds
      if: github.ref == 'refs/heads/main'  # Only runs on main branch

      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '21'

        - name: Publishing
          run:  ./gradlew publishAllPublicationsToGitLabRepository --stacktrace

        - name: Setup tmate session
          if: ${{ failure() }}
          uses: mxschmitt/action-tmate@v3
